post_controllers:
    resource: ../../src/Post/UI/Controller/
    type: attribute

user_controllers:
    resource: ../../src/User/UI/Controller/
    type: attribute

kernel:
    resource: App\Kernel
    type: attribute
